appname = casnode
httpport = 7000
runmode = dev
SessionOn = true
copyrequestbody = true
redisEndpoint =
driverName = mysql
dataSourceName = root:123456@tcp(82.156.59.217:3306)/
dbName = casnode
domain = "forum.casbin.com"
casdoorDbName = casdoor
casdoorOrganization = "casbin-forum"
casdoorApplication = "casnode-app"
casdoorStorageEndpoint = "https://cdn.casbin.com/"
casdoorEndpoint = http://localhost:8000
clientId = b05b737580ebded0c144
clientSecret = 1702df600d16571368a2d9ccd79cf4105629f10e
httpProxy = "127.0.0.1:10808"
initScore = 2000
enableNestedReply = true
cacheExpireSeconds = 60
